// DO NOT EDIT Code automatically generated.
// Generated by: go run github.com/pierrec/packagen/cmd/packagen -v single -nogen -o slice_bytes.go -prefix Bytes -mvtype Item=Bytes -rmtype Item slice.go
package slice

type BytesSlice []Bytes // this type and its methods will be implemented and renamed with the relevant chosen type

func (s BytesSlice) Min() Bytes {
	var m Bytes
	for _, v := range s {
		if v := Bytes(v); v.Less(m) {
			m = v
		}
	}
	return m
}
func (s BytesSlice) Max() Bytes {
	var m Bytes
	for _, v := range s {
		if v := Bytes(v); m.Less(v) {
			m = v
		}
	}
	return m
}
